name: CI

on:
  merge_group:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Remove cargo config for incremental builds
        run: rm -f .cargo/config.toml

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
        if: runner.os == 'linux'

      - name: Cache rust modules
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          shared-key: ubuntu-build

      - name: Build tests
        run: cargo test --features blobs --no-run

      - name: Run tests
        run: cargo test --features blobs

      - name: Build all examples
        run: ./build-examples.sh

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove cargo config for incremental builds
        run: rm -f .cargo/config.toml

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove cargo config for incremental builds
        run: rm -f .cargo/config.toml

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - run: cargo clippy --all-features -- -D warnings

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove cargo config for incremental builds
        run: rm -f .cargo/config.toml

      - uses: dtolnay/rust-toolchain@nightly

      - name: doc
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: -Dwarnings
